config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                    path('admin/', admin.site.urls),
                    path('', include('dogs.urls', namespace='dogs')),
                    path('users/', include('users.urls', namespace='users')),
                ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.views import index, categories, category_dogs, dogs_list_view, dog_create_view, dog_detail_view, dog_delete_view, dog_update_view

from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/dogs/', category_dogs, name='category_dogs'),
    path('dogs/', dogs_list_view, name='list_dogs'),
    path('dogs/create/', dog_create_view, name='create_dog'),
    path('dogs/detail/<int:pk>/', dog_detail_view, name='detail_dog'),
    path('dogs/update/<int:pk>/', dog_update_view, name='update_dog'),
    path('dogs/delete/<int:pk>/', dog_delete_view, name='delete_dog'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_register_view, user_login_view, user_profile_view, user_logout_view, user_update_view, \
    user_change_password_view, user_generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name='login_user'),
    path('logout/', user_logout_view, name='logout_user'),
    path('register/', user_register_view, name='register_user'),
    path('profile/', user_profile_view, name='profile_user'),
    path('update/', user_update_view, name='update_user'),
    path('change_password/', user_change_password_view, name='change_password_user'),
    path('profile/genpassword', user_generate_new_password, name='user_generate_new_password')
]

dogs/models.py
from django.db import models
from django.conf import settings
from users.models import NULLABLE

class Category (models.Model):
    name = models.CharField(max_length=100, verbose_name='breed')
    description = models.CharField(max_length=1000, verbose_name='descriptions')

    def __str__(self):
            return f'{self.name}'

    class Meta:
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'


class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='dog_name')
    # category = models.CharField(max_length=100, verbose_name='breed')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='breed')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='image')
    birth_date = models.DateField(**NULLABLE, verbose_name='birth_date')


    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='владелец')
    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'dog' # понятное человеку имя модели
        verbose_name_plural = 'dogs' # понятное человеку имя множественное число
        # abstaract = True # Данная модель станет абстракным базовым классом
        # app_label = 'dogs' # если модель определена за пределами app., то момжно таким образом ее к нему отнести
        # ordering =  [-1] # Изменение порядка полей модели
        # proxy = True # модель будет рассматривться как проки модель
        # permessions = [] # добавляются группы пользователей которые могут изменять сущность данной модели
        # db_table = 'doggies' # перезаписть ия таблицы в БД
        # get_latest_by = 'birth_date' # Возвращает последний объект по порядку возрастания (самая молодая собака)

dogs/forms.py
from django import forms
import datetime
from dogs.models import Dog
from users.forms import StyleFormMixin


# class DogForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Dog
#         fields = '__all__'

class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        exclude = ('owner',)

    # def clean_birth_date(self):
    #     cleaned_data = self.cleaned_data['birth_date']
    #     now_year = datetime.datetime.now().year
        # if now_year - cleaned_data.year > 100:
        #     raise forms.ValidationError('Собака должна быть моложе 100 лет')
# class DogUpdateForm(StyleFormMixin, forms.ModelForm):
#     class Meta:
#         model = Dog
#         exclude = ('owner',)

dogs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from dogs.models import Category, Dog
from dogs.forms import DogForm


def index(request):
    context = {
        'object_list': Category.objects.all()[:3],
        'title': 'Питомник - Главная'
    }
    return render(request, 'dogs/index.html', context)


@login_required
def categories(request):
    context = {
        'object_list': Category.objects.all(),
        'title': 'Питомник - Все наши породы'
    }
    return render(request, 'dogs/categories.html', context)


@login_required
def category_dogs(request, pk):
    category_item = Category.objects.get(pk=pk)
    context = {
        'object_list': Dog.objects.filter(category_id=pk),
        'title': f'Собаки породы - {category_item.name}',
        'category_pk': category_item.pk,
    }
    return render(request, 'dogs/dogs.html', context)


@login_required
def dogs_list_view(request):
    context = {
        'object_list': Dog.objects.all(),
        'title': 'Питомник - Все наши собаки',
    }
    return render(request, 'dogs/dogs.html', context)


@login_required
def dog_create_view(request):
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES)
        if form.is_valid():
            dog_object = form.save()
            dog_object.owner = request.user
            dog_object.save()
            form.save()
            return HttpResponseRedirect(reverse('dogs:list_dogs'))
    context = {
        'title': 'Добавление питомца',
        'form': DogForm(),
    }
    return render(request, 'dogs/create_update.html', context)


@login_required
def dog_detail_view(request, pk):
    context = {
        'object': Dog.objects.get(pk=pk),
        'title': 'Вы выбрали данного питомца'
    }
    return render(request, 'dogs/detail.html', context)


@login_required
def dog_update_view(request, pk):
    # dog_object = Dog.objects.get(pk=pk)
    dog_object = get_object_or_404(Dog, pk=pk)
    print(request)
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES, instance=dog_object)
        if form.is_valid():
            dog_object = form.save()
            dog_object.save()
            return HttpResponseRedirect(reverse('dogs:detail_dog', args={pk: pk}))
    context = {
        'object': dog_object,
        'form': DogForm(instance=dog_object)
    }
    return render(request, 'dogs/create_update.html', context)


@login_required
def dog_delete_view(request, pk):
    dog_object = get_object_or_404(Dog, pk=pk)
    if request.method == 'POST':
        dog_object.delete()
        return HttpResponseRedirect(reverse('dogs:list_dogs'))
    return render(request, 'dogs/delete.html', {
        'object': dog_object,
    })

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:categories' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:list_dogs' %}" class="text-white">Собаки</a></li>
                        <li><a href="{% url 'dogs:create_dog' %}" class="text-white">Добавить собаку</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile_user' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout_user' %}" class="text-white">Выход</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login_user' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:register_user' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/categories.html
{% extends 'dogs/base.html' %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
            {% include 'dogs/includes/inc_category.html' with object=object %}
        {% endfor %}
    </div>

{% endblock %}

dogs/templates/dogs/create_update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование собаки
                {% else %}
                Добавление собаки
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top"
                     src="{{ object.photo|dogs_media }}" width="300" height="320"
                     alt="Card image cap">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>

            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Вы уверены что хотите удалить собаку
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top"
                     src="{{ object.photo|dogs_media }}" width="300" height="320"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text>">{{ object.name|title }}</p>
                </div>

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger">
                    {% if object %}
                    Удалить
                    {% endif %}

                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-mb-4">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="320"
                 alt="Card image cap">
            <div class="card-text">
                <p class="text-text">{{ object.name|title }}</p>
                <span class="text-muted">{{ object.birth_date|default:"-" }}</span><br>
                <span class="text-muted">{{ object.owner|default:"Без хозяина" }}</span>
            </div>
            <div class="card-footer">
                <a class="btn btn-link" href="{% url 'dogs:update_dog' object.pk %}">обновить</a>
                <a class="btn btn-link" href="{% url 'dogs:delete_dog' object.pk %}">удалить</a>
            </div>

    </div>
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
    {% for object in object_list %}
    <div class="col-mb-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="320"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
            </div>
            <div>
                <a class="btn btn-link" href="{% url 'dogs:detail_dog' object.pk %}">подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_category.html' with object=object %}
    {% endfor %}
</div>

{% endblock %}