config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                    path('admin/', admin.site.urls),
                    path('', include('dogs.urls', namespace='dogs')),
                    path('users/', include('users.urls', namespace='users')),
                ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.views import index, categories, category_dogs, dogs_list_view, dog_create_view, dog_detail_view, dog_delete_view, dog_update_view

from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/dogs/', category_dogs, name='category_dogs'),
    path('dogs/', dogs_list_view, name='list_dogs'),
    path('dogs/create/', dog_create_view, name='create_dog'),
    path('dogs/detail/<int:pk>/', dog_detail_view, name='detail_dog'),
    path('dogs/update/<int:pk>/', dog_update_view, name='update_dog'),
    path('dogs/delete/<int:pk>/', dog_delete_view, name='delete_dog'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_register_view, user_login_view, user_profile_view, user_logout_view, user_update_view, \
    user_change_password_view, user_generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name='login_user'),
    path('logout/', user_logout_view, name='logout_user'),
    path('register/', user_register_view, name='register_user'),
    path('profile/', user_profile_view, name='profile_user'),
    path('update/', user_update_view, name='update_user'),
    path('change_password/', user_change_password_view, name='change_password_user'),
    path('profile/genpassword', user_generate_new_password, name='user_generate_new_password')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    first_name = models.CharField(max_length=150, verbose_name='First Name', default='Anonymous')
    last_name = models.CharField(max_length=150, verbose_name='Last Name', default='Anonymous')
    phone = models.CharField(max_length=35, verbose_name='Phone number', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='Telegram Username', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='active')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']
        # abstract = True # данная модель станет абстрактным базовым классом
        # app_label = 'users' # если модель определена за пределами app., то таким образом можно ее к нему отнести
        # ordering = [-1] # изменение порядка полей в модели
        # proxy = True # модель будет рассматриваться как прокси модель
        # permissions = [] # добавляются группы пользователей которые могут изменять сущность данной модели
        # db_table = 'my_users' # перезаписать имя таблицы в БД
        # get_latest_by = 'birth_date' # возвращает последний объект по порядку возрастания (самый молодой пользователь)

users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from users.models import User
from users.validators import validate_password
from django.contrib.auth.forms import PasswordChangeForm

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone',)


class UserRegisterForm(StyleFormMixin, forms.ModelForm):
    # password = forms.CharField(label='Пароль', widget=forms.PasswordInput, min_length=6, max_length=12)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        temp_data = self.cleaned_data
        print(temp_data)
        validate_password(temp_data['password'])
        if temp_data['password'] != temp_data['password2']:
            print('Пароли не совпадают!!!')
            raise forms.ValidationError('Пароли не совпадают!!!')
        return temp_data['password2']


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)


class UserPasswordChangeForm(StyleFormMixin, PasswordChangeForm):
    pass

users/views.py
import random
import string

from django.http import HttpResponseRedirect, HttpResponse

from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required

from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserPasswordChangeForm
from  users.services import send_register_email, send_new_password

def user_register_view(request):
    form = UserRegisterForm(request.POST) # POST
    if request.method == 'POST':
        if form.is_valid(): # Если форма валидна сохраняет введеные данные
            new_user = form.save()
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            send_register_email(new_user.email)
            return HttpResponseRedirect(reverse('users:login_user'))
    context = {
        'form': form
    }
    return render(request, 'users/register_user.html', context)


def user_login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(email=cd['email'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('dogs:index'))
                else:
                    return HttpResponse('Аккаунт неактивен!')

    form = UserLoginForm
    context = {
        'form': form
    }
    return render(request, 'users/login_user.html', context)

@login_required
def user_profile_view(request):
    user_object = request.user
    if user_object.first_name:
        user_name = user_object.first_name
    else:
        user_name = "Anonymous"
    context = {
        # 'user_object': user_object,
        'title': f'Ваш профиль {user_name}',
        # 'form': UserForm(instance=user_object),
    }
    return render(request, 'users/user_profile_read_only.html', context)

@login_required
def user_update_view(request):
    user_object = request.user
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=user_object)
        if form.is_valid():
            user_object = form.save()
            user_object.save()
            return HttpResponseRedirect(reverse('user:profile_user'))
        user_name = user_object.first_name
        context = {
            'user_object': user_object,
            'title': f'изменит профиль {user_name}',
            'form': UserUpdateForm(instance=user_object)
        }
        return render(request, 'users/update_user.html', context)

def user_change_password_view(request):
    user_object = request.user
    form = UserPasswordChangeForm(user_object, request.POST)
    if request.method == "POST":
        if form.is_valid():
            user_object = form.save()
            update_session_auth_hash(request, user_object)
            messages.success(request, "Пароль был успешно изменен!")
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            messages.error(request, "Не удалось изменить пароль!")

    context = {
        'form': form
    }
    return render(request, 'users/change_password_user.html', context)

def user_logout_view(request):
    logout(request)
    return redirect('dogs:index')

@login_required()
def user_generate_new_password(request):
    new_password = ''.join(random.sample((string.ascii_letters + string.digits), 12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/users/change_password_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Изменение пароля
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Авторизация пользователя</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Регистрация пользователя</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/update_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Редактирование пользователя
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <form enctype="multipart/form-data">
                    {{ form.as_p }}
                    <button class="btn btn-outline-warning">
                        <a class="btn btn-link" href="{% url 'users:update_user' %}">обновить</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile_read_only.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <span class="card-text">Почта: {{user.email}}</span><br>
                <span class="card-text">Имя: {{user.first_name}}</span><br>
                <span class="card-text">Фамилия: {{user.last_name}}</span><br>
                <span class="card-text">Телефон: {{user.phone|default:"Не указано"}}</span><br>
                <span class="card-text">Телеграмм-аккаунт: {{user.telegram|default:"Не указано"}}</span><br>
                <button class="btn btn-outline-primary">
                    <a class="btn btn-link" href="{% url 'users:change_password_user' %}">изменить пароль</a>
                </button>
                <button class="btn btn-outline-danger">
                    <a class="btn btn-link" href="{% url 'users:user_generate_new_password' %}">генерация пароля</a>
                </button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}